#pragma once

#include "fmc-hardware-mapping.h"
#include "usbdevice.h"

#include <cstdint>
#include <string>
#include <vector>

// LED index constants — subset of FMCLed from fmc-aircraft-profile.h.
enum StressFMCLed : uint8_t {
    STRESS_LED_BACKLIGHT = 0,
    STRESS_LED_SCREEN_BACKLIGHT = 1,
    STRESS_LED_OVERALL_BRIGHTNESS = 2,
    STRESS_LED_MCDU_START = 8,
    STRESS_LED_MCDU_END = 16,
};

// Subclass of USBDevice that drives an MCDU device for the stress test.
// It uses USBDevice::connect() / writeData() / disconnect() from usbdevice_win.cpp
// exactly as-is. Only the FMC-specific init sequence and display logic live here.
class StressFMC : public USBDevice {
    public:
        static constexpr unsigned int PageLines = 14;
        static constexpr unsigned int PageCharsPerLine = 24;
        static constexpr unsigned int PageBytesPerChar = 3;
        static constexpr unsigned int PageBytesPerLine = PageCharsPerLine * PageBytesPerChar;
        static constexpr uint8_t identifierByte = 0x32; // MCDU hardware identifier

        StressFMC(HIDDeviceHandle hidDevice, uint16_t vendorId, uint16_t productId, std::string vendorName, std::string productName);
        ~StressFMC() override;

        bool connect() override;
        const char *classIdentifier() override;

        // Update the display with a scrolling Lorem Ipsum. Each row starts at
        // (scrollOffset + rowIndex) in the text, so every row is different and
        // the device must repaint the full screen each call.
        void drawScrollingText(int scrollOffset);

        void setLedBrightness(uint8_t led, uint8_t brightness);
        void setAllLedsEnabled(bool enable);

        // Selectable fonts, read from the .xpwwf files in fonts/ next to the
        // exe (or the repository's fonts/ when run from a build directory).
        // Index 0 is the font uploaded by connect().
        static size_t fontCount();
        static const char *fontName(size_t index);
        static const char *fontFileName(size_t index);

        // Multi-line report of where fonts were looked for, what was found, and
        // the shape of each file. Written to the diagnostics log so an empty font
        // list can be told apart from a font that fails to upload.
        static std::string fontsReport();
        void loadFont(size_t index);

        // Runs the plugin's real font pipeline for the given hardware type:
        // Font::GlyphData() -> Font::ResizeCellHeight() -> upload -> screen
        // position, exactly as ProductFMC::setFont() does. The device address
        // byte stays 0x32 whatever the hardware type, so PFP geometry (23x32,
        // origin 14/4) can be pushed to an MCDU: the only difference from a real
        // PFP upload is which device the packets are addressed to. That isolates
        // the ResizeCellHeight rebuild from the hardware itself.
        // Returns the number of packets sent, 0 on failure.
        size_t loadFontForHardware(size_t index, FMCHardwareType hardwareType);

        // What the last loadFontForHardware() call did: geometry, whether
        // ResizeCellHeight rebuilt the font, packet count. Kept so the guided
        // diagnostic run can put it in the log.
        std::string lastUploadReport = {};

        // Font uploads performed since this device was opened. The hardware appears
        // to accept only the first font-set commit per USB session, so any test
        // result has to be read together with this number.
        int uploadsSinceConnect = 0;

        // Writes every font x every hardware geometry through the real pipeline to
        // .bin files next to the exe, without touching the device. Lets the
        // generated bytes be analysed offline instead of asking someone to read a
        // screen. Returns the number of files written.
        static size_t dumpAllFontsAndGeometries();

        // Fills the screen with the printable ASCII range so a glyph the device
        // failed to store shows up as a blank cell. Used to check an upload.
        void drawGlyphSheet();

    private:
        void sendInitPackets();
        void showBackground_WINCTRL_LOGO();
        void showBackgroundBlack();

        // SimAppPro "Screen Position" packet, copied from
        // ProductFMC::setScreenPosition(): left = 36 + x, top = 20 + y.
        void setScreenPosition(unsigned char x, unsigned char y);
};
